# Generated by Django 2.0.4 on 2018-05-05 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Chapter'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answers',
            field=models.ManyToManyField(to='book.Answer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
