# Generated by Django 2.0.4 on 2018-05-14 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Chapter'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='answers',
        ),
        migrations.AddField(
            model_name='profile',
            name='answers',
            field=models.ManyToManyField(null=True, to='book.Answer'),
        ),
    ]
