# Generated by Django 2.0.4 on 2018-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180514_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answers',
            field=models.ManyToManyField(to='book.Answer'),
        ),
    ]
