# Generated by Django 2.0.4 on 2018-05-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180514_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_chapter', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Profile')),
            ],
        ),
    ]
